### ISSUE TITLE
Add marking points for hand joints

### ISSUE THREAD

**Issue by anubis-tyrant** [opendreamnet/dreampower#119]
Just like there are marking points for belly button and the pubic part, it would be great if you could add points for hands as well like elbows and wrist and shoulder joint. It would help a lot in full clothes, or some other situations where hand marking is needed

**Comment by Pingasmaster** [comment]
Agreed, it could lead to better results, but also will lead to much more complexity (more heavier datasets, new training required, more processing power and RAM required), adding even more time to the image generation process. The ideal way would be implementing it as on option, but it would still require a heavier database and re-coding entire parts of the software. As I do not have the mandatory knowledge for this, I can't do it. If anyone can, well, I'm sure it will be a good improvement.

Hoping to have been useful, please close the issue if this comment solved your problem.
