### ISSUE TITLE
Latest Colab?

### ISSUE THREAD

**Issue by osushilover** [opendreamnet/dreampower#123]
I am pleased with your work; the level of completeness is really professional!
Do you guys have any plan to release the code for Google Colab?
Unfortunately, I can't run the code on my local machine due to some poor factors.

**Comment by gurachan** [comment]
i dont think xD google allowed this stuff .. they even go far as changing the name

**Comment by osushiski** [comment]
> i dont think xD google allowed this stuff .. they even go far as changing the name

Exactly🙄
Doesn't power of dream extend to Google?

**Comment by cedspam** [comment]
Basically  you just need a notebook file including basic setup and command to run,  it doesn't really need to have any relationship with google at first collaboratory except a link to launch it on this service

**Comment by kolessios** [comment]
Please visit: https://www.dreamtime.tech/docs/guide/google-colab
