### ISSUE TITLE
Plans to incorporate stable diffusion?

### ISSUE THREAD

**Issue by jasonborn0** [opendreamnet/dreampower#150]
**Is your feature request related to a problem? Please describe.**
As titled. 

**Describe the solution you'd like**
Swap out deepnude with sd.

**Describe alternatives you've considered**

**Additional context**

**Comment by kolessios** [comment]
Thank you for your interest in DreamPower, the project has been discontinued and we are now focusing our efforts on SukebeZone+ which you can find more information on:

https://sukebezone.com/
